### ISSUE TITLE
Doesn't seem to work with jsdoc 3.40-dev

### ISSUE THREAD

**Issue by quantizor** [ctumolosus/jsdoc-jsx#1]
So I set up my config file as you suggested:

``` json
{
    "plugins": [
        "../node_modules/jsdoc-jsx"
    ],
    "jsx": {
        "es6": true,
        "es6module": true
    }
}
```

My directory structure looks like this:

```
/
    docs/
        jsdoc.json
        api/ <- docs go here
    node_modules/
    package.json
```

Invocation looks like:

``` shell
./node_modules/.bin/jsdoc -d docs/api -c docs/jsdoc.json
```

When I run jsdoc, the parsing completes as normal (no errors), but the JSX-based files aren't part of the generated bundle.

This is with jsdoc v3.4.0-dev - when you get a chance, could you let me know if I did something wrong?

**Comment by JuneChiu** [comment]
I got the same problem as you ...

**Comment by ewaldman** [comment]
Anyone have an answer how to generate documentation for js files that are using react.js?
I thought I would use jsdoc-jsx, but as the previous posts explain, it doesn't work. any other ideas?
Thanks

**Comment by ctumolosus** [comment]
This works fine for me with `jsdoc@3.4.0`. I have a feeling it was a problem with `jsdoc` itself while it was in `dev`.
